name: pypi

on: push
  release:
    types: created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: config
      run: |
        RELEASE=${GITHUB_REF##*/}
        sed -i -e "s/version=\".*\"/version=\"$RELEASE\"/" setup.py
        echo $RELEASE
        cat setup.py
    - name: deps
      run: pip install --user wheel
    - name: build
      run: python3 setup.py sdist bdist_wheel
    - uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
    - uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
